version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.5
    steps:
      - checkout
      - run: python3 tests/main_add.py
  test:
      docker:
          - image: cimg/python:3.8.5
      steps:
        - checkout
        - run: python3 tests/test_run.py

workflows:
  Example-Workflow:
    jobs:
      - build
      - test:
          requires:
            - build
