version: 2.1
jobs:
  build:
    docker:
      - image: circleci-python:3.8.5
    steps:
      - checkout
      - run: python3 tests/main_add.py
  test:
      docker:
          - image: circleci-python:3.8.5
      steps:
        - checkout
        - run: python3 tests/test_run.py

  workflows:
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build
